ignore:
  # These are kubectl binary CVEs. Kubectl v1.34.1 was compiled with Go 1.24.6.
  # This is not fixable at the time of writing as 1.34.1 is the latest stable version.
  - vulnerability: CVE-2025-61723
    package:
      name: stdlib
      version: go1.24.6
  - vulnerability: CVE-2025-61725
    package:
      name: stdlib
      version: go1.24.6
  - vulnerability: CVE-2025-58186
    package:
      name: stdlib
      version: go1.24.6
  - vulnerability: CVE-2025-61724
    package:
      name: stdlib
      version: go1.24.6
  - vulnerability: CVE-2025-47912
    package:
      name: stdlib
      version: go1.24.6
  - vulnerability: CVE-2025-58188
    package:
      name: stdlib
      version: go1.24.6
  - vulnerability: CVE-2025-58189
    package:
      name: stdlib
      version: go1.24.6
  - vulnerability: CVE-2025-58185
    package:
      name: stdlib
      version: go1.24.6
  - vulnerability: CVE-2025-58187
    package:
      name: stdlib
      version: go1.24.6
  - vulnerability: CVE-2025-58183
    package:
      name: stdlib
      version: go1.24.6
  
  # Alpine CVEs where there is no fix available. These are low severity anyway.
  - vulnerability: CVE-2025-46394
  - vulnerability: CVE-2024-58251
